apiVersion: v1
kind: Service
metadata:
  name: iotconsumer-svc
  labels:
    app: iotconsumer
spec:
  type: NodePort
  selector:
     app: iotconsumer
  ports:
  - port: 8000
    targetPort: iotconsumerport
    protocol: TCP
    nodePort: 31888