apiVersion: v1
kind: Secret
metadata:
  name: iotconsumer-sc
type: Opaque
data:
  dbpwd: <your encoded value>                 
  iotauthkey: <your encoded value> 
  iotauthtoken: <your encoded value>    