apiVersion: v1
kind: Service
metadata:
  name: iotconsumer-svc
  labels:
    app: iotconsumer
spec:
  type: NodePort
  ports:
  - port: 8000 # Internal Port
    protocol: TCP
    nodePort: 31513
  selector:
    app: iotconsumer